CREATE TABLE IF NOT EXISTS groups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS criteria (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  roles TEXT NOT NULL DEFAULT 'TOUS',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS teams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  manager TEXT
);

CREATE TABLE IF NOT EXISTS collaborators (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS surveys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  reference TEXT,
  date TEXT NOT NULL,
  collaborator_id INTEGER NOT NULL REFERENCES collaborators(id),
  role TEXT NOT NULL CHECK(role IN ('TITULAIRE', 'AGENT_B', 'RENFORT', 'EA')),
  evaluator TEXT,
  status TEXT NOT NULL DEFAULT 'EN_COURS' CHECK(status IN ('EN_COURS', 'FINALISEE')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS survey_evaluations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  survey_id INTEGER NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  criteria_id INTEGER NOT NULL REFERENCES criteria(id),
  value TEXT NOT NULL DEFAULT 'NON_EVALUE' CHECK(value IN ('NON_EVALUE', 'CONFORME', 'PARTIEL', 'NON_CONFORME')),
  comment TEXT,
  UNIQUE(survey_id, criteria_id)
);
